# Site settings
title: VR.net
tag_text: VR.net
description: 
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["README.md"]
sass:
  style: compressed
